// Import dependencies that is needed to create the episode entity.
using System.ComponentModel.DataAnnotations; // Import attributes for data validation.
using System.ComponentModel.DataAnnotations.Schema; // Import attributes for database schema mapping.
using IntegrityVault.Common.Enums;// Import enums to get the entity common.


// Define the namespace for the entity classes in the IntegrityVault project.
namespace IntegrityVault.Common.Entities
{
    // Declare the class Episode.
    public class Episode
    {
        // Primary key for the Episode table. Value is auto generated by the database.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }


        // Foreign key referencing the patient this episode belongs to. It is required.
        [Required]
        public required int PatientID { get; set; }

        // Navigation property to the related patient entity.
        [ForeignKey("PatientID")]
        public Patient? Patient { get; set; }


        // Foreign key referencing the doctor managing this episode. It is required.
        [Required]
        public required int DoctorID { get; set; }

        // Navigation property to the related doctor entity.
        [ForeignKey("DoctorID")]
        public Doctor? Doctor { get; set; }


        // The medical specialty this episode falls under.
        [Required]
        public required DoctorSpecialty Specialty { get; set; }


        // A short administrative title describing the clinical issue.
        [Required]
        [StringLength(120, MinimumLength = 3, ErrorMessage = "Title must be between 3 and 120 characters.")]
        public required string Title { get; set; }


        // Whether this episode is still an ongoing treatment or closed.
        [Required]
        public bool IsActive { get; set; } = true;


        // Date on which this episode was opened.
        [Required]
        public required DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        

        // Navigation property representing all visit records belonging to this episode.
        public virtual ICollection<MedicalRecord> Records { get; set; } = new HashSet<MedicalRecord>();
    }
}
