// Import dependencies that is needed to create the hospital ip address entity.
using System.ComponentModel.DataAnnotations; // Import attributes for data validation.
using System.ComponentModel.DataAnnotations.Schema; // Import attributes for database schema mapping.


// Define the namespace for the entity classes in the IntegrityVault project.
namespace IntegrityVault.Common.Entities
{
    // Declare the class HospitalIpAddress.
    public class HospitalIpAddress
    {
        // Primary key for the HospitalIpAddress table. Value is auto generated by the database.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // Foreign key back to Hospital.
        [Required]
        public int HospitalID { get; set; }

        // Navigation property back to the owning hospital.
        public virtual Hospital Hospital { get; set; } = null!;

        // The public IP address (IPv4 or IPv6).
        [Required]
        [StringLength(45)]
        public required string IpAddress { get; set; }
    }
}
