// Import dependencies that is needed to create the hospital entity.
using System.ComponentModel.DataAnnotations; // Import attributes for data validation.
using System.ComponentModel.DataAnnotations.Schema; // Import attributes for database schema mapping.


// Define the namespace for the entity classes in the IntegrityVault project.
namespace IntegrityVault.Common.Entities
{
    // Declare the class Hospital.
    public class Hospital
    {
        // Primary key for the Hospital table. Value is auto generated by the database.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // Hospital's name. It is required and limited to 100 characters.
        [Required]
        [StringLength(100)]
        public required string Name { get; set; }

        // Hospital's blockchain wallet address. It is required and must be exactly 42 characters long.
        [Required]
        [StringLength(42, MinimumLength = 42, ErrorMessage = "Wallet address must exactly 42 characters long.")]
        public required string WalletAddress { get; set; }

        // Navigation property representing all ipaddress associated with this hospital.
        public virtual ICollection<HospitalIpAddress> IpAddresses { get; set; } = new HashSet<HospitalIpAddress>();

        // Navigation property representing all users associated with this hospital.
        public virtual ICollection<User> Users { get; set; } = new HashSet<User>();
    }
}
