// Import dependencies that is needed to create the medical record entity.
using System.ComponentModel.DataAnnotations; // Import attributes for data validation.
using System.ComponentModel.DataAnnotations.Schema; // Import attributes for database schema mapping.


// Define the namespace for the entity classes in the IntegrityVault project.
namespace IntegrityVault.Common.Entities
{
    // Declare the class MedicalRecord.
    public class MedicalRecord
    {
        // Primary key for the MedicalRecord table. Value is auto generated by the database.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // Foreign key refrencing the patient and is required.
        [Required]
        public required int PatientID { get; set; }

        // Navigation property to the related patient entity.
        [ForeignKey("PatientID")]
        public Patient? Patient { get; set; }

        // Foreign key refrencing the doctor and is required.
        [Required]
        public required int DoctorID { get; set; }

        // Navigation property to the related doctor entity.
        [ForeignKey("DoctorID")]
        public Doctor? Doctor { get; set; }

        // Medical record's IPFS CID. It is required, limited to 90 characters, and must be at least 40 characters.
        [Required]
        [StringLength(90, MinimumLength = 40, ErrorMessage = "IPFS CID must be at least 40 characters.")]
        public required string IPFS_CID{ get; set; }

        // Track how many times this record has been updated.
        [Required]
        public int CurrentVersion { get; set; } = 0;

        // Date on which the medical record was created.
        [Required]
        public required DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Date on which the medical record was updated.
        [Required]
        public required DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        // Navigation property representing all accessed logs associated with this medical record.
        public virtual ICollection<RecordAccessLog> AccessLogs { get; set; } = new HashSet<RecordAccessLog>();

        // Navigation propety representing the full update history of this medical record.
        public virtual ICollection<MedicalRecordAuditLog> AuditLogs { get; set; } = new HashSet<MedicalRecordAuditLog>();
    }
}
