// Import dependencies that is needed to create the record access log entity.
using System.ComponentModel.DataAnnotations; // Import attributes for data validation.
using System.ComponentModel.DataAnnotations.Schema; // Import attributes for database schema mapping.
using IntegrityVault.Common.Enums; // Import custom enums from the project.

// Define the namespace for the entity classes in the IntegrityVault project.
namespace IntegrityVault.Common.Entities
{
    // Declare the class RecordAccessLog.
    public class RecordAccessLog
    {
        // Primary key for the MedicalRecord table. Value is auto generated by the database.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // Foreign key refrencing the medical record and is required.
        [Required]
        public required int RecordID { get; set; }

        // Navigation property to the related medical record entity.
        [ForeignKey("RecordID")]
        public MedicalRecord? Record { get; set; }

        // Foreign key refrencing the user who access the record and is required.
        [Required]
        public required int AccessedByUserID { get; set; }

        // Navigation property to the related user entity.
        [ForeignKey("AccessedByUserID")]
        public User? AccessedBy { get; set; }

        // How the record was accessed. It is required.
        [Required]
        public required AccessType AccessType { get; set; }

        // Date and time which the medical record was accessed.
        [Required]
        public required DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }
}
