// Import dependencies that is needed to create the user entity.
using System.ComponentModel.DataAnnotations; // Import attributes for data validation.
using System.ComponentModel.DataAnnotations.Schema; // Import attributes for database schema mapping.
using IntegrityVault.Common.Enums; // Import custom enums from the project.


// Define the namespace for the entity classes in the IntegrityVault project.
namespace IntegrityVault.Common.Entities
{
    // Declare the abstract class user.
    public abstract class User
    {
        // Primary key for the User table. Value is auto generated by the database.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // User's username. It is required, and limited to 100 characters.
        [Required]
        [StringLength(100)]
        public required string Username { get; set; }

        // User's email. It is required, limited to 255 characters and must be in a valid email address format.
        [Required]
        [StringLength(255)]
        [EmailAddress]
        public required string Email { get; set; }

        // User's password. It is required, limited to 255 characters, and must be at least 7 characters.
        [Required]
        [StringLength(255, MinimumLength = 7, ErrorMessage = "Password must at least 7 characters.")]
        public required string Password { get; set; }

        // Role assigned to the user and is required.
        [Required]
        public required UserRole Role { get; set; }

        // Date the user join the system.
        [Required]
        public DateTime JoinDate { get; set; } = DateTime.UtcNow;

        // Foreign key refrencing the associated hospital and is optional.
        public int? HospitalID { get; set; }

        // Navigation property to the related hospital entity.
        [ForeignKey("HospitalID")]
        public Hospital? Hospital { get; set; }
    }
}
