// <auto-generated />
using System;
using IntegrityVault.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrityVault.Repository.Migrations
{
    [DbContext(typeof(IntegrityVaultDbContext))]
    partial class IntegrityVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegrityVault.Common.Entities.Episode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<byte>("Specialty")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Episodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Episode_Specialty", "[Specialty] IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Episode_Title_MinLength", "LEN(Title) >= 3");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Hospital", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("ID");

                    b.HasIndex("WalletAddress")
                        .IsUnique();

                    b.ToTable("Hospitals", null, t =>
                        {
                            t.HasCheckConstraint("CK_Hospitals_WalletAddress_Length", "LEN(WalletAddress) = 42");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.HospitalIpAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HospitalID")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("ID");

                    b.HasIndex("HospitalID", "IpAddress")
                        .IsUnique();

                    b.ToTable("HospitalIpAddresses", (string)null);
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BlockchainTxHash")
                        .HasMaxLength(66)
                        .IsUnicode(false)
                        .HasColumnType("varchar(66)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EpisodeID")
                        .HasColumnType("int");

                    b.Property<string>("IPFS_CID")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("PreviousVersionHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("VersionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.HasIndex("EpisodeID");

                    b.ToTable("MedicalRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedicalRecord_BlockchainTxHash_Length", "BlockchainTxHash IS NULL OR LEN(BlockchainTxHash) = 66");

                            t.HasCheckConstraint("CK_MedicalRecord_ContentHash_Length", "LEN(ContentHash) = 64");

                            t.HasCheckConstraint("CK_MedicalRecord_CurrentVersion_NonNegative", "CurrentVersion >= 0");

                            t.HasCheckConstraint("CK_MedicalRecord_PreviousVersionHash_Length", "PreviousVersionHash IS NULL OR LEN(PreviousVersionHash) = 64");

                            t.HasCheckConstraint("CK_MedicalRecord_VersionHash_Length", "LEN(VersionHash) = 64");

                            t.HasCheckConstraint("CK_Medical_Record_IPFS_CID_Length", "LEN(IPFS_CID) >= 40");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.MedicalRecordAuditLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BlockchainTxHash")
                        .HasMaxLength(66)
                        .IsUnicode(false)
                        .HasColumnType("varchar(66)");

                    b.Property<string>("NewContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NewIPFS_CID")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("NewVersionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PreviousContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PreviousIPFS_CID")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("PreviousVersionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UpdatedByDoctorID")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UpdatedByDoctorID");

                    b.HasIndex("RecordID", "Version")
                        .IsUnique();

                    b.ToTable("MedicalRecordAuditLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_BlockchainTxHash_Length", "BlockchainTxHash IS NULL OR LEN(BlockchainTxHash) = 66");

                            t.HasCheckConstraint("CK_AuditLog_CIDs_Must_Differ", "PreviousIPFS_CID <> NewIPFS_CID");

                            t.HasCheckConstraint("CK_AuditLog_ContentHashes_Must_Differ", "PreviousContentHash <> NewContentHash");

                            t.HasCheckConstraint("CK_AuditLog_NewContentHash_Length", "LEN(NewContentHash) = 64");

                            t.HasCheckConstraint("CK_AuditLog_NewIPFS_CID_Length", "LEN(NewIPFS_CID) >= 40");

                            t.HasCheckConstraint("CK_AuditLog_NewVersionHash_Length", "LEN(NewVersionHash) = 64");

                            t.HasCheckConstraint("CK_AuditLog_PreviousContentHash_Length", "LEN(PreviousContentHash) = 64");

                            t.HasCheckConstraint("CK_AuditLog_PreviousIPFS_CID_Length", "LEN(PreviousIPFS_CID) >= 40");

                            t.HasCheckConstraint("CK_AuditLog_PreviousVersionHash_Length", "LEN(PreviousVersionHash) = 64");

                            t.HasCheckConstraint("CK_AuditLog_VersionHashes_Must_Differ", "PreviousVersionHash <> NewVersionHash");

                            t.HasCheckConstraint("CK_AuditLog_Version_Positive", "Version >= 1");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.RecordAccessLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte>("AccessType")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint");

                    b.Property<int>("AccessedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ID");

                    b.HasIndex("AccessedByUserID");

                    b.HasIndex("RecordID");

                    b.ToTable("RecordAccessLogs", null, t =>
                        {
                            t.HasCheckConstraint("Ck_RecordAccessLog_AccessType", "[AccessType] IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("HospitalID")
                        .HasColumnType("int")
                        .HasAnnotation("HospitalID", "This property must be set for Patients, Doctors, and Admins");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Role")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HospitalID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_HospitalID_Required", "(Role IN (0, 1, 2, 3) AND HospitalID IS NOT NULL) OR (Role IN (4) AND HospitalID IS NULL)");

                            t.HasCheckConstraint("CK_Users_Email_Format", "Email LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Users_Password_Length", "LEN(Password) >= 7");

                            t.HasCheckConstraint("Ck_User_Role", "[Role] IN (0, 1, 2, 3, 4)");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Admin", b =>
                {
                    b.HasBaseType("IntegrityVault.Common.Entities.User");

                    b.ToTable("Admins", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_HospitalID_Required", "(Role IN (0, 1, 2, 3) AND HospitalID IS NOT NULL) OR (Role IN (4) AND HospitalID IS NULL)");

                            t.HasCheckConstraint("CK_Users_Email_Format", "Email LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Users_Password_Length", "LEN(Password) >= 7");

                            t.HasCheckConstraint("Ck_User_Role", "[Role] IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Doctor", b =>
                {
                    b.HasBaseType("IntegrityVault.Common.Entities.User");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Specialty")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint");

                    b.ToTable("Doctors", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_HospitalID_Required", "(Role IN (0, 1, 2, 3) AND HospitalID IS NOT NULL) OR (Role IN (4) AND HospitalID IS NULL)");

                            t.HasCheckConstraint("CK_Users_Email_Format", "Email LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Users_Password_Length", "LEN(Password) >= 7");

                            t.HasCheckConstraint("Ck_User_Role", "[Role] IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("Ck_Doctor_Specialty", "[Specialty] IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.ExternalProvider", b =>
                {
                    b.HasBaseType("IntegrityVault.Common.Entities.User");

                    b.Property<int>("BelongsToID")
                        .HasColumnType("int");

                    b.HasIndex("BelongsToID");

                    b.ToTable("ExternalProviders", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_HospitalID_Required", "(Role IN (0, 1, 2, 3) AND HospitalID IS NOT NULL) OR (Role IN (4) AND HospitalID IS NULL)");

                            t.HasCheckConstraint("CK_Users_Email_Format", "Email LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Users_Password_Length", "LEN(Password) >= 7");

                            t.HasCheckConstraint("Ck_User_Role", "[Role] IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Patient", b =>
                {
                    b.HasBaseType("IntegrityVault.Common.Entities.User");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Gender")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("Patients", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_HospitalID_Required", "(Role IN (0, 1, 2, 3) AND HospitalID IS NOT NULL) OR (Role IN (4) AND HospitalID IS NULL)");

                            t.HasCheckConstraint("CK_Users_Email_Format", "Email LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Users_Password_Length", "LEN(Password) >= 7");

                            t.HasCheckConstraint("Ck_User_Role", "[Role] IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("Ck_Patient_Gender", "[Gender] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.SuperAdmin", b =>
                {
                    b.HasBaseType("IntegrityVault.Common.Entities.User");

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasIndex("WalletAddress")
                        .IsUnique()
                        .HasFilter("[WalletAddress] IS NOT NULL");

                    b.ToTable("SuperAdmins", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_HospitalID_Required", "(Role IN (0, 1, 2, 3) AND HospitalID IS NOT NULL) OR (Role IN (4) AND HospitalID IS NULL)");

                            t.HasCheckConstraint("CK_Users_Email_Format", "Email LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Users_Password_Length", "LEN(Password) >= 7");

                            t.HasCheckConstraint("Ck_User_Role", "[Role] IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_SuperAdmin_WalletAddress_Length", "LEN(WalletAddress) = 42");
                        });
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Episode", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.Doctor", "Doctor")
                        .WithMany("Episodes")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.Patient", "Patient")
                        .WithMany("Episodes")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.HospitalIpAddress", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.Hospital", "Hospital")
                        .WithMany("IpAddresses")
                        .HasForeignKey("HospitalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.MedicalRecord", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.Episode", "Episode")
                        .WithMany("Records")
                        .HasForeignKey("EpisodeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.MedicalRecordAuditLog", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.MedicalRecord", "Record")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.Doctor", "UpdatedByDoctor")
                        .WithMany()
                        .HasForeignKey("UpdatedByDoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Record");

                    b.Navigation("UpdatedByDoctor");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.RecordAccessLog", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.User", "AccessedBy")
                        .WithMany()
                        .HasForeignKey("AccessedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.MedicalRecord", "Record")
                        .WithMany("AccessLogs")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessedBy");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.User", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.Hospital", "Hospital")
                        .WithMany("Users")
                        .HasForeignKey("HospitalID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Admin", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.Admin", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.Admin", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Doctor", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.Doctor", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.Doctor", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.Doctor", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.ExternalProvider", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.Hospital", "BelongsTo")
                        .WithMany()
                        .HasForeignKey("BelongsToID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.ExternalProvider", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.ExternalProvider", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.ExternalProvider", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BelongsTo");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Patient", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.Patient", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.Patient", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.Patient", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.SuperAdmin", b =>
                {
                    b.HasOne("IntegrityVault.Common.Entities.SuperAdmin", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.SuperAdmin", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrityVault.Common.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("IntegrityVault.Common.Entities.SuperAdmin", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Episode", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Hospital", b =>
                {
                    b.Navigation("IpAddresses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.MedicalRecord", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Doctor", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("IntegrityVault.Common.Entities.Patient", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
